spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-inventario
          uri: lb://MICROSERVICE-INVENTARIO
          predicates:
            - Path=/inventario/**


        - id: ms-usuario
          uri: lb://MICROSERVICE-USUARIO
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter

        - id: ms-producto
          uri: lb://MICROSERVICE-PRODUCTO
          predicates:
            - Path=/product/**
          filters:
            - AuthenticationFilter


  application:
    name: API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 30
    fetch-registry: true
    register-with-eureka: true
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90


jwt:
  secret: ${SECRET:ueesmgra-123540}
