server:
  port: ${PORT:${SERVER_PORT:0}}
  servlet:
    context-path: /product
  error:
    include-message: always

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 30
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

spring:
  application:
    name: MICROSERVICE-PRODUCTO
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password-msvc-product}
    url: jdbc:postgresql://${DB_HOST:localhost:5532}/${DB_DATABASE:db-msvc-product}
    hikari:
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      minimum-idle: 5
      maximumPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

url:
  ms:
    inventario:
      insumo: http://MICROSERVICE-INVENTARIO/inventario/insumo-detalle/traerInsumoDetalle
