
variables:
  DOCKER_DRIVER: overlay2
  
stages:
 - build
 - deploy


docker-build-push-image:
  stage: build
  services:
   - docker:dind
  before_script:
  # Docker HUB login
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

  script:

    - docker build -t $DOCKER_HUB_USERNAME/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_HUB_USERNAME/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
    - docker tag $DOCKER_HUB_USERNAME/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA $DOCKER_HUB_USERNAME/$CI_PROJECT_NAME:latest
    - docker push $DOCKER_HUB_USERNAME/$CI_PROJECT_NAME:latest

docker-deploy-microservice:
  needs:
    - job: docker-build-push-image
  image: docker/compose
  stage: deploy 
  services:
   - docker:dind

  script:
    - docker-compose version
    - docker-compose up -d
    - sleep 5
    - docker ps
    - sleep 5
    - docker ps
    - sleep 5
    - docker ps
    - sleep 5
    - sleep 5
    - docker-compose down -v
